base_url = "https://miguelpimentel.do/zola-testing/"
title = "Zola Testing"
description = "This repo is used to test new web elements. It is an amalgamation of code snippets, all weaved together by Zola."
compile_sass = true
generate_feed = false
minify_html = false
build_search_index = false
taxonomies = [
  { name = "categories", feed = false },
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
# highlight_theme = "ayu-light"

[extra]
internalLinks = [
  { url = "test", name = "Test" },
  { url = "posts", name = "Posts" },
  { url = "posts/markdown-showcase", name = "Showcase" },
  { url = "projects", name = "Projects" },
  { url = "projects/discord-in-sidebar", name = "GitHub in Sidebar" },
]
# externalLinks = [
#   { url = "https://miguelpimentel.do/", name = "Blog" },
#   { url = "https://foretfulnotes.com/", name = "Garden" },
#   { url = "https://github.com/semanticdata/", name = "GitHub" },
# ]
